name: 'OpenAPI to Notion Action'
description: 'Converts OpenAPI definitions to Notion pages'
inputs:
  notion-token:
    description: 'Notion API token'
    required: true
  config-file:
    description: 'Path to the configuration file'
    required: false
  config:
    description: 'Configuration YAML'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: sudo apt install git-restore-mtime
      shell: bash

    - name: Prepare repository
      run: git restore-mtime
      shell: bash

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Download JAR file
      run: |
        curl -L -o app.jar https://github.com/PaoloConte/openapi-to-notion/releases/download/v1.6.2/app.jar
      shell: bash

    - name: Prepare Config File
      env:
        NOTION_TOKEN: ${{ inputs.notion-token }}
        CONFIG_FILE: ${{ inputs.config-file }}
        CONFIG: ${{ inputs.config }}
      run: |
        # Determine the config file path to use
        if [ -n "$CONFIG_FILE" ]; then
          CONFIG_PATH=$CONFIG_FILE
        else
          # If CONFIG_FILE is not provided, use CONFIG to create a temp file
          echo "$CONFIG" > /tmp/config.yml
          CONFIG_PATH=/tmp/config.yml
        fi
        echo "CONFIG_PATH=${CONFIG_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Execute Java Program
      run: java -jar app.jar --config-file ${{ env.CONFIG_PATH }}
      shell: bash
      env:
        NOTION_TOKEN: ${{ inputs.notion-token }}
